/*
 * ULP specific FCBS interface
 *
 * Broadcom Proprietary and Confidential. Copyright (C) 2016,
 * All Rights Reserved.
 * 
 * This is UNPUBLISHED PROPRIETARY SOURCE CODE of Broadcom;
 * the contents of this file may not be disclosed to third parties, copied
 * or duplicated in any form, in whole or in part, without the prior
 * written permission of Broadcom.
 *
 * <<Broadcom-WL-IPTag/Open:>>
 *
 * $Id: fcbs.h 619302 2016-02-16 06:49:16Z $
 */

#ifndef	_ULP_FCBS_H_
#define	_ULP_FCBS_H_

#include <fcbsutils.h>
#include <d11regs.h>
#include <osl.h>
#include <siutils.h>

#define	FCBS_ROM_SEQ_DISABLE	0xABCDABCD

typedef struct fcbs_info fcbs_info_t;
typedef struct fcbs_info * fcbs_info_t_p;

enum {
	FCBS_DS0,	/* 0 */
	FCBS_DS1,	/* 1 */
	FCBS_DS_MAX,
	};

typedef struct fcbs_out {
	uint32 cmd_start;
	uint32 dat_start;
} fcbs_out_t;

enum {
	FCBS_SEQ_IN_ROM = 1,
	FCBS_SEQ_IN_RAM = 2
};

/* Reference:
 * http://confluence.broadcom.com/display/WLAN/BCM43012+Driver+UCODE+Interface
 */
enum {
#ifdef BCMULP
	FCBS_DS1_MAC_INIT_BLOCK,	/* 0 */
	FCBS_DS1_PHY_RADIO_BLOCK,	/* 1 */
	FCBS_DS1_RADIO_PD_BLOCK,	/* 2 */
	FCBS_DS1_EXIT_BLOCK,		/* 3 */
	FCBS_DS0_RADIO_PU_BLOCK,	/* 4 */
	FCBS_DS0_RADIO_PD_BLOCK,	/* 5 */
#else
	FCBS_DS0_RADIO_PU_BLOCK,	/* 0 */
	FCBS_DS0_RADIO_PD_BLOCK,	/* 1 */
#endif /* BCMULP */
};

#define M_FCBS_DS1_MAC_INIT_BLOCK_SZ	8
#define M_FCBS_DS1_PHY_RADIO_BLOCK_SZ	16
#define M_FCBS_DS1_RADIO_PD_BLOCK_SZ	4
#define M_FCBS_DS1_EXIT_BLOCK_SZ	4
#define M_FCBS_DS0_RADIO_PU_BLOCK_SZ	2
#define M_FCBS_DS0_RADIO_PD_BLOCK_SZ	2

/* sequence id's used by FCBS Blocks */
enum {
	/* ************************************** */
	/* ROM Data                               */
	/* Idx in fcbs_input_ctrl$fcbs_input_data */
	/* ************************************** */

	/* host interrupt */
	TRIGGER_HOST_INTERRUPT	= 0,
	/* init seqs */
	INIT_PHY_REGS		= 1,
	INIT_PHY_TBLS		= 2,
	/* Misc phy functions */
	FUNC_DEAF		= 3,
	FUNC_RETURN_FROM_DEAF	= 4,
	FUNC_TBL_SETUP		= 5,
	FUNC_TBL_CLEANUP	= 6,
	FUNC_PHY_RESET		= 7,
	FUNC_NAPPING		= 8,
	/* pd seqs */
	PWR_DN_RADIO		= 9,

	/* initvals */
	FCBSROM_ULP_INITVALS	= 10,
	FCBSROM_ULP_BSINITVALS	= 11,
	FCBSROM_PAPD_WAVEFORM	= 12,

	/* ************************************** */
	/* RAM Data                               */
	/* Idx in ulp_fcbs$fcbs_ds1_phy_radio_blk */
	/* ************************************** */

	/* Dynamic seqs */
	CHANSPEC_PHY_RADIO	= 5,
	CALCACHE_PHY_RADIO	= 6,

	/* Exec seq */
	DS1_EXEC_MINIPMU_PU	= 9,
	DS1_EXEC_PLL_PU		= 10,
	EXEC_NAPPING		= 4,

	/* DS0 exec seq */
	DS0_EXEC_MINIPMU_PU	= 0,
	DS0_EXEC_PLL_PU		= 1,
	DS0_EXEC_RADIO_PD	= 0
};

/* FCBS_DS1_MAC_INIT_BLOCK */
#define FCBS_DYN_MAC_INIT_BLK_AMT_SEQ	2

/* FCBS_DS1_EXIT_BLOCK */
#define FCBS_DS1_EXIT_BLOCK_SEQ0	0

/* === Chip spedicific data: For Chip:43012 Rev: A0 [END] === */

/* The following arrays are generated by FCBS ROM generator tool */
extern uint8 fcbs_metadata[];
extern uint8 fcbs_ram_data[];

extern int ulp_fcbs_init(si_t *sih, osl_t *osh, int ds_inx);

/*
 * This function adds/updates an FCBS dynamic sequence for a give block and
 * sequence number.
 *
 * fid: FCBS input data structure
 * blk_num: Block number
 * seq_num: Execution sequence number
 */
extern void ulp_fcbs_add_dynamic_seq(fcbs_input_data_t *fid,
		int blk_num, int seq_num);

/*
 * This function updates the FCBS ROM sequence number for a give block and
 * sequence number.
 *
 * blk_num: Block number
 * seq_num: Execution sequence number
 * rom_seq_num:
 *      - FCBS ROM sequence number
 *      - Pass FCBS_ROM_SEQ_DISABLE to disable this sequence
 */
extern void ulp_fcbs_update_rom_seq(int blk_num, int seq_num, int rom_seq_num);

/* If the FCBS sequence is in FCBS ROM then cmd_ptr and dat_ptr points to the addresses in
 * FCBS ROM. In case, if the sequence got abandoned, then cmd_ptr and dat_ptr points to
 * the addresses of the abandoned data present in ARM RAM.
 */
extern int fcbs_rom_metadata(int rom_seq_num, fcbs_tuples_t *ft);

bool is_fcbs_initialized(void);

/* attach and detach infra */
extern void BCMATTACHFN(fcbs_detach)(void);
extern fcbs_info_t_p BCMATTACHFN(fcbs_attach)(osl_t *osh, si_t *sih, d11regs_t *regs);

/* fcbs populate core function
 * INPUT ARGS:
 * 1. Formatted raw data in for a given stage (formatted ==> fcbs_input_data_t)
 * 2. num of sequences for that stage
 */
extern fcbs_out_t fcbs_populate(fcbs_input_data_t *input, int num_tuples, int ds_inx);
extern int fcbs_reset_cmd_dat_ptrs(int ds_inx);

#endif	/* _ULP_FCBS_H_ */
